language: node_js
sudo: false

node_js:
  - '12'

branches:
  only:
  - master

env:
  global:
  - LOGS_DIR=/tmp/angular-material2-build/logs
  - SAUCE_USERNAME=angular-ci
  - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
  - BROWSER_STACK_USERNAME=angularteam1
  - BROWSER_STACK_ACCESS_KEY=BWCd4SynLzdDcv8xtzsB
  - BROWSER_PROVIDER_READY_FILE=/tmp/angular-material2-build/readyfile
  - BROWSER_PROVIDER_ERROR_FILE=/tmp/angular-material2-build/errorfile
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
    - MODE=lint
    - MODE=aot
    - MODE=payload
    - MODE=e2e
    - MODE=saucelabs_required
    - MODE=browserstack_required

matrix:
  fast_finish: true
  allow_failures:
  - env: "MODE=saucelabs_optional"
  - env: "MODE=browserstack_optional"

install:
  - npm install

before_script:
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/build-and-test.sh

after_success:
  - ./scripts/ci/after-success.sh

cache:
  directories:
    - node_modules
    - $HOME/.pub-cache
